# Use Node.js image for the build stage
FROM node:20 AS build-stage

WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install

# Copy the rest of the files and build the frontend
COPY . .
RUN pnpm run build

# Use Nginx for serving the built files
FROM nginx:1.21

# Copy the built files from the build stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copy the Nginx configuration files
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

