# Get Node v20 image as the build stage
FROM node:20 AS build-stage

# Create working directory
WORKDIR /app

# Install the dependancies
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm i

# Copy the rest of the files
COPY . .

# Build
RUN pnpm run build

# Get the nginx image
FROM nginx:1.21

# Copy the built files to nginx image
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the nginx server to the port 80
EXPOSE 80

