# Get the Node image
FROM node:iron-alpine3.20

# Create the working directory
WORKDIR /app

# Install the dependancies
COPY package.json pnpm-lock.yaml ./
RUN npm i -g pnpm
RUN pnpm i

# Copy all the remaining files
COPY . .

# Expose the server to port 5000
EXPOSE 5000

# Start the server
CMD ["node", "server.js"]
